### ISSUE TITLE
Getting Error When Using StripeFactoryService

### ISSUE THREAD

**Issue by saascharge** [richnologies/ngx-stripe#105]
I am using the following version:
"ngx-stripe": "^7.4.5",

bug report?
Everything works fine for me when setting the key in module:

`NgxStripeModule.forRoot('<my-pub-key'),`

However, when I use the following (from a sub Angular module):

`NgxStripeModule.forRoot(),`

```
import { StripeCardComponent, CardSetupResult, StripeInstance, StripeFactoryService } from 'ngx-stripe';
import {
  StripeCardElementOptions,
  StripeElementsOptions,
} from '@stripe/stripe-js';

@Component({
  selector: 'ngx-sc-create-token',
  templateUrl: './sc-guest-payment.html',
  styleUrls: ['./sc-guest-payment.scss'],
})
export class ScSampleComponent implements OnInit {

  @ViewChild(StripeCardComponent) card: StripeCardComponent;

  elementsOptions: StripeElementsOptions;
  stripe: StripeInstance;

  cardOptions: StripeCardElementOptions = {
    style: {
      base: {
        iconColor: '#666EE8',
        color: '#31325F',
        fontWeight: '300',
        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
        fontSize: '18px',
        '::placeholder': {
          color: '#CFD7E0',
        },
      },
    },
  };

  stripeForm: FormGroup;

  constructor(
    private stripeFactory: StripeFactoryService,
    private scApi: ScService,
    private fb: FormBuilder) {
      this.stripe = this.stripeFactory.create('pk_test_........');
    this.elementsOptions = {
    };
    }

  ngOnInit(): void {
    this.stripeForm = this.fb.group({
      name: ['', [Validators.required]],
    });
  }
```

HTML looks like this:

`<ngx-stripe-card [options]="cardOptions" [elementsOptions]="elementsOptions"></ngx-stripe-card>
`
I get the following JS error:

```
core.js:15724 ERROR TypeError: Cannot read property 'elements' of undefined
    at StripeService.push../node_modules/ngx-stripe/fesm5/ngx-stripe.js.StripeService.elements (ngx-stripe.js:540)
```
Again, if I use the forRoot option everything works well. What am I missing when using StripeFactoryService?

**Comment by richnologies** [comment]
Hi @saascharge, thanks for the issue. With all this information is much easier to work.

To answer your question, the problem is you are not passing your stripe instance to the component. So, instead of:

`<ngx-stripe-card [options]="cardOptions" [elementsOptions]="elementsOptions"></ngx-stripe-card>`

try:

`<ngx-stripe-card [options]="cardOptions" [elementsOptions]="elementsOptions" [stripe]="stripe"></ngx-stripe-card>`

If you don't pass to the component your stripe instance it will try to use the default. The default is only created when you pass your key to the `forRoot` call. I prepare a complete example for you in Stackblitz:

https://stackblitz.com/edit/ngx-stripe-issue-105?file=src/app/examples/create-token/create-token.component.ts

Please notice also in the example how I call `createToken` method on the stripe instance also, not the stripe service.

Hope this helps.

Also, the version number is of the library you are using is little bit confusing. `7.4.5` is the legacy version of the library. I highly recommend you upgrade to one of the LTS versions, the one that match your Angular major version if possible, more info here: https://richnologies.gitbook.io/ngx-stripe/getting-started/installation

The solution should work on both versions of the library, but the legacy don't have many of the new APIs available in Stripe.

Please let me know if works.

R

**Comment by saascharge** [comment]
Thank you a lot for getting back - I will trying now and I will surely let you know.
