### ISSUE TITLE
Did the border bottom amongst other styles ever get fixed?

### ISSUE THREAD

**Issue by jalvini** [richnologies/ngx-stripe#113]
Hello, I was just wondering if the border bottom and other style options have been added? I am on the latest version and still do not have that option.

**Comment by richnologies** [comment]
Hi @jalvini, I'm not sure if a I understand your question. What I can tell is that since version 10, we have refactor to library to use `@stripe/stripe-js` interfaces, so we no longer maintain our own types. 

If I get your question right, I think the styles that Stripe currently support are these: https://stripe.com/docs/js/appendix/style

Please, if I get it wrong, provide more info so a I can give a more specific answer. Otherwise, I suggest to open an issue in the @stripe/stripe-js repo: https://github.com/stripe/stripe-js

Thanks,

R
