### ISSUE TITLE
Card element not working in Safari

### ISSUE THREAD

**Issue by phansen-nd** [richnologies/ngx-stripe#129]
**Is this a feature request or a bug report?**

Bug report

**What's gone wrong?**

Using the `<ngx-stripe-card>` tag in a form, it works as expected in Chrome, Firefox, and Opera, but the element is not visible in Safari (latest version, `14.0.3`). It seems to be there, as hovering over shows the input cursor and Safari brings up saved cards, but it's invisible.

**What was meant to happen?**

Trying to let the user input card details.

**Steps to reproduce**

Visit <a href="https://kayak-rental.web.app/reserve">this site</a> in Safari. You will have to navigate through the form to the "Confirm" tab (you may have to pick tomorrow's date in the datepicker to get to a valid reservation time). You can fill in dummy info for contact details.

**Other information**

Node 14.2.0
npm 6.14.8
Angular CLI 10.2.3
ngx-stripe 11.0.0

<img width="1225" alt="Screen Shot 2021-05-14 at 3 42 22 PM" src="https://user-images.githubusercontent.com/12384992/118335566-2ceda800-b4cd-11eb-979b-e76d9a06d0f9.png">
<img width="789" alt="Screen Shot 2021-05-14 at 3 45 02 PM" src="https://user-images.githubusercontent.com/12384992/118335569-2eb76b80-b4cd-11eb-9f8e-962b605b0491.png">

**Comment by richnologies** [comment]
Hi @phansen-nd,

I follow your steps in Safari and the card is visible for me. Did you fix it or do you think I'm doing something wrong?

If you fix it, it would be great to know what the problem was to help other developers. If you don't, feel free to contact me directly and I will be happy to help you

![image](https://user-images.githubusercontent.com/4794630/118337152-71039b80-b513-11eb-83c5-8956cc16a7ca.png)

**Comment by phansen-nd** [comment]
@richnologies thanks for the speedy reply!

I haven't done anything to fix it. I'm happy to hear it's working in some configuration. I will try to do some more extensive testing and narrow down what the issue is on my machine since it is happening every time.

Thanks!

**Comment by phansen-nd** [comment]
![IMG_20210517_203034](https://user-images.githubusercontent.com/12384992/118581415-da232300-b74e-11eb-8a97-66b2eae25f63.jpg)

@richnologies here is another screenshot of the invisible card element from safari on a mobile device. Are you able to reproduce this? Seems like it's still an intermittent problem.

**Comment by richnologies** [comment]
Hi @phansen-nd, one question. It seems is not the only thing invisible in your screenshoots. I cannot see the email or the phone. Is that expected? (Maybe you hide them for privacy) I just want to be sure :)

**Comment by richnologies** [comment]
Hi again @phansen-nd, I'm able to reproduce this error on my iPad. 
It looks it's a problem with the stripe element. Take a look at this issue: https://github.com/stripe/stripe-js/issues/128
They suggest a workaround. I've connected my device to the laptop and run this commands from the console and it works for me. 
As you can see in the comments, the problem seems to be related to animations, so the idea is to run this code after the animation has ended. 

> ```js
> 
>   if (el) {
>     const initialDisplay = el.style.display;
> 
>     el.style.display = 'none';
>     el.offsetHeight;
>     el.style.display = initialDisplay;
>   }
> }
> 
> 
> // Force the Element frame to paint once it is visible on the page
> forceReflow('.StripeElement');
> ```

**Comment by phansen-nd** [comment]
Thank you @richnologies !

**Comment by sherz12r** [comment]
i used this but in my case still not working in iphone 8 browser label is showing but input not showing please help
![WhatsApp Image 2023-08-31 at 23 00 22](https://github.com/richnologies/ngx-stripe/assets/46225971/d9f3b62a-b23a-4e06-a6ea-ada92426f0da)
