### ISSUE TITLE
How to display CVC number as password  type (****)

### ISSUE THREAD

**Issue by shreyshahh** [richnologies/ngx-stripe#131]
I want CVC number to be shown as password type, like dots for security purpose instead of showing the numbers directly. Any way this can be achieved?

**Comment by richnologies** [comment]
Hi @shreyshahh,

I'm afraid as of this moment we don't have that ability. Stripe Elements does not have support for that yet since is not a PCI requirement. As you can see in the following issues open in Stripe repos there is an interest on this feature, but no updates so far. 

https://github.com/stripe/react-stripe-js/issues/167
https://github.com/stripe/react-stripe-elements/issues/328
