### ISSUE TITLE
stripe-js error?

### ISSUE THREAD

**Issue by patrickchoi** [richnologies/ngx-stripe#138]
This error message didn't really tell me much. Any ideas?

`ERROR in node_modules/@stripe/stripe-js/types/stripe-js/token-and-sources.d.ts(106,48): error TS2304: Cannot find name 'unknown'.`

Installed to Angular 6 project using:

`npm install ngx-stripe@v6-lts @stripe/stripe-js`

Getting the error when trying to load the page, using lazy loading. Here's the module:

```
@NgModule({
  imports: [
    SharedModule,
    CommonModule,
    PaymentRoutingModule,
    NgxStripeModule.forChild('pk_test_xxxxxxxxxxx'),
    TranslateModule.forChild({
      loader: {
        provide: TranslateLoader,
        useFactory: (createTranslateLoader),
        deps: [HttpClient]
      }
    })
  ],
  declarations: [PaymentComponent]
})
export class PaymentModule { }
```

**Comment by richnologies** [comment]
Hi @patrickchoi,

Thanks for submitting the issue. So, basically, Angular 6 is quite an older version now. If I'm not mistaken you're using typescript@2. The problem is Typescript introduce a new kind of `any` name `unknown` on v3 and `@stripe/stripe-js` is using that type. 

So you have two options:

1. Upgrade Angular to a newer version that at least uses Typescript 3
2. Install an older version of the loader, something from `1.12.1` will do: `npm i @stripe/stripe-js@1.12.1`
3. A hacky trick, declare `unknown` yourself, for example by adding this code to your `main.ts` file:
```typescript
export type mixed = { [key: string]: any } | object | number | string | boolean | symbol | undefined | null | void

declare global {
  type unknown = mixed
}
```

Option 2 is obviously way easier, however older versions of `stripe-js` miss some of the newer payment methods and features. Version `1.12.1` is from `Feb 2021` so you should be fine by now. 

If you really need latests features, you can go with option 3, but do not forget to remove it if you ever upgrade to `Typescript@3`.

Thanks to bring this issue to my attention, I will add some peerDependencies so users will get more accurate error messages :) 

Hope this helps. If you need anything else do not hesitate to ask

R

**Comment by patrickchoi** [comment]
Thanks that did it! Downgraded to stripe-js 1.12.1.
