### ISSUE TITLE
Module '"../../../../../../node_modules/ngx-stripe/ngx-stripe"' has no exported member 'Elements', 'StripeElement', 'ElementsOptions'.

### ISSUE THREAD

**Issue by anoop-kiwi** [richnologies/ngx-stripe#140]
Hello Team,

I'm getting the below errors while using the ngx-stripe module.

1. Module '"../../../../../../node_modules/ngx-stripe/ngx-stripe"' has no exported member 'Elements'.
2. Module '"../../../../../../node_modules/ngx-stripe/ngx-stripe"' has no exported member 'Element'.
3. Module '"../../../../../../node_modules/ngx-stripe/ngx-stripe"' has no exported member 'ElementsOptions'.

Imported Command:

import { StripeService, Elements, Element as StripeElement, ElementsOptions } from 'ngx-stripe';

Angular CLI Version: 11.2.12
Ngx-Stripe Version: 11.1.0
TS Version: 4.1.5

Let me know if you have required anything else.

Thanks in advance.
Anoop

**Comment by richnologies** [comment]
Hi @anoop-kiwi,

There have been a few changes last year in the library. Basically, we move away from our own types and start using the `@stripe/stripe-js` official ones because it makes the library more aligned with the latest changes from Stripe and much easier to maintain from our side. 

Unfortunately there was not good way to make this changes backwards compatible, so this is our only breaking change ever. The old version that it seems you have been using is what we now call **legacy**. Here you have a table with some npm tags available to install each version depending on your Angular major version: https://github.com/richnologies/ngx-stripe#installation. As you can see, v9 was the last version we support for the **legacy** branch. 

Here is a list of all the major changes: https://github.com/richnologies/ngx-stripe/blob/main/MIGRATION.md. They look like a loot but is basically naming, for example, in your case:

First of all you need to install **@stripe/stripe-js** since is now a peer dependency of the library: `npm i @stripe/stripe-js`, then:

- Elements become StripeElements (from `@stripe/stripe-js`)
- Element become StripeElement (from `@stripe/stripe-js`)
- ElementsOptions become StripeElementOptions (from `@stripe/stripe-js`)

We also have a new docs page that hopefully can help you: https://docs.ngx-stripe.dev
In particular, here is a simple example of collecting a Payment Intent: https://docs.ngx-stripe.dev/examples#collect-payment-intent

Sorry about the inconvenience of the migration. If you have any more questions or need any help, please do not hesitate to ask :)

Kind regards

R

**Comment by anoop-kiwi** [comment]
Hi @richnologies ,

You saved my day. It's working as I want. 

Your new [integration document](https://docs.ngx-stripe.dev/getting-started/installation) is mind-blowing.
