### ISSUE TITLE
Question of stripe public key management

### ISSUE THREAD

**Issue by sebyoga** [richnologies/ngx-stripe#144]
Hello @richnologies,

Your module works perfectly, however, I have a small question.  

My client has one stripe account, but several sub-entities and therefore several sub-accounts.

Considering that the key is imported globally on the angular application, what is the way to be able to define it at the funnel of the payment (it is a choice present during the payment funnel...).

Thanks a lot for your answer,

Have a nice day,
Sébastien

**Comment by richnologies** [comment]
Hi @sebyoga,

Thanks for the feedback. 

Importing the key globally is the default way since is by far the most common scenario.

For cases like yours we have another service called StripeFactory. Check the example bellow, and please check a few things

- We don't pass the stripe key to the `forRoot` method
- The `StripeInstance` object implements the same interface as the StripeService, so it has the same methods.
- You need to pass the stripe object to your component

https://docs.ngx-stripe.dev/core-concepts/service-factory

If you have any questions, please let me know. 

R

**Comment by sebyoga** [comment]
Hi @richnologies,

Thank you for the quick response, it is much appreciated.

After various tests, everything seems to work perfectly. Thank you very much!

Have a nice day,
Sébastien
