### ISSUE TITLE
Support for Angular v15

### ISSUE THREAD

**Issue by justvamp** [richnologies/ngx-stripe#187]
Angular 15 is released, it would be great to support it. Thanks!

**Comment by richnologies** [comment]
Hi @justvamp,

I'm working on the new version. It might take a few more days because I want to fully support Standalone Components and to deprecate some internal artefacts that should never been exposed. 

Thanks for your patience

R

**Comment by justvamp** [comment]
Sounds amazing! Thank you for the fastest reply, patiently waiting :)

**Comment by Dzivo** [comment]
@richnologies that is nice.
 for now just use --force on npm install if you are not going to production it does work for me

**Comment by ahmadallw** [comment]
hi @justvamp, 
Any new good news about the new version?

Thank you!

**Comment by ArthurBardakov** [comment]
@richnologies Hi! Any progress on the support of Angular 15? It would be great to have an update on that!

**Comment by richnologies** [comment]
Hi everyone!

Sorry about the delay. We have been working on both fronts, adding new features from Stripe and working with the Standalone API from Angular in case we need to introduce any breaking changes. 

So, two new versions shipped today:

- `14.3.0` Including a lot of the latest Stripe features -- check the CHANGELOG if you're interested
- `15.0.0` The same new version with support for Angular v15

The version for Angular v15 does not include yet support for Standalone components because we are still doing some test, but we can release this version now because we are certain now we won't introduce any breaking changes. 

Again, sorry for any inconvenience

Let me know if you have any issues with the new version

Kind Regards

R

**Comment by s2young** [comment]
If it helps, I am using standalone components.  I'm trying to access StripeFactoryService on my component and it's not there.  Is there any way to provide it or instantiate it manually?

**Comment by richnologies** [comment]
Hey @s2young, happy to discuss this issue with you. Do you mind to create a separate issue?
