### ISSUE TITLE
[BUG]No provider for StripeService!

### ISSUE THREAD

**Issue by atefnajar** [richnologies/ngx-stripe#218]
R3InjectorError(PaymentModule)[StripeService -> StripeService -> StripeService -> StripeService]: 
  NullInjectorError: No provider for StripeService!
NullInjectorError: R3InjectorError(PaymentModule)[StripeService -> StripeService -> StripeService -> StripeService]: 
  NullInjectorError: No provider for StripeService!
version 15.7.1 , 15.6.1,1 ???

**Comment by richnologies** [comment]
Hi @atefnajar,

I'm gonna need way more details in order to help you. What version of Angular, NgxStripe and @stripe/stripe-js are you using and a code snippet showing how are you using the library. Are you adding the NgxStripeModule¿, are you using Standalone¿ etc... Any details you can provide that will help me replicate the problem.

Thanks in advance,

R

**Comment by timothydodd** [comment]
Hi @richnologies ,

I also run into this issue if I am lazy loading a feature module (with out `app.module.ts`  importing  `NgxStripeModule` ) and the module is setup like so

``` TypeScript
const maskConfig: Partial<IConfig> = {
  validation: false,
};

@NgModule({
  declarations: [
    RegisterPageComponent
  ],
  imports: [
    CommonModule,
    NgxStripeModule.forRoot(environment.stripe.publishKey)
  ],
  exports: [PurchasePageComponent],
  providers: [provideNgxMask(maskConfig)]
})
export class PurchaseModule { }
```

The only way I can resolve the issue is if I import the module to the `app.module.ts` as well.
