### ISSUE TITLE
[BUG] Card icon not visible

### ISSUE THREAD

**Issue by corentingosselin** [richnologies/ngx-stripe#245]
**Describe the bug**

The icon card is not visible with this configuration:

```
cardOptions: StripeCardElementOptions = {
    iconStyle: 'default',
    hideIcon: false,
    style: {
      base: {
        iconColor: 'white',
        color: 'white',
        fontWeight: '300',
        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
        fontSize: '18px',
        '::placeholder': {
          color: '#CFD7E0',
        },
      },
    },
  };
```
![Capture d’écran 2024-02-23 à 17 29 36](https://github.com/richnologies/ngx-stripe/assets/8132994/5bec235c-88fd-482b-b2a6-5a9634a508b3)

If I remove the is-hidden class from chrome inspector it works:

![Capture d’écran 2024-02-23 à 17 45 21](https://github.com/richnologies/ngx-stripe/assets/8132994/a25b0864-537e-4799-b575-4758d146c36a)

Version ngx-stripe: 17.1.1

**Comment by richnologies** [comment]
Hey @corentingosselin,

Sorry for the delay, but just for future reference, when using Card Number, Card Expiry and Card CVV separately, the option is showIcon and not hideIcon. This is a Stripe API, not Ngx Stripe specific. I think the reason is, showing the icon is the default behaviour for the Stripe Card Element, but not for the Stripe Card Number Element. 

When you're using the three elements separately options should be of type `StripeCardNumberElementOptions` and not `StripeCardElementOptions`
