### ISSUE TITLE
Support for different elementType on stripeCardComponent

### ISSUE THREAD

**Issue by mbastakoti** [richnologies/ngx-stripe#28]
Looks like the type of the cardComponent is currently being defaulted to 'card'. Is there any way to currently use different card types while using stripeCardComponent?

Thanks

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.
