### ISSUE TITLE
Additional styles and validations

### ISSUE THREAD

**Issue by erezsharir** [richnologies/ngx-stripe#34]
I'm having a couple of issues with the component:
1 - I can't set all the styles that I want on the inner elements (for example: background color, border, border radius).
Since the content is inside an iframe, I can't set the style by css.

2 - I want the form submit button to be disabled until all the data is entered, but this information is missing (hooking "on" is just not enough)

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.
