### ISSUE TITLE
paymentRequestButton

### ISSUE THREAD

**Issue by akshayverma172** [richnologies/ngx-stripe#39]
Argument of type '"paymentRequestButton"' is not assignable to parameter of type 'ElementType'.

From your previous issue i tried that code but its not working anymore. Please can you have this fixed. Any help would be really appreciated.

Thanks

**Comment by SUVOLewis** [comment]
Still having this problem, did you ever solve it?

**Comment by dottodot** [comment]
Can you provide some more info such as which version you are using and your code so can we can have a look.

**Comment by elucidsoft** [comment]
I believe he is referring to this documentation here: https://stripe.com/docs/stripe-js/elements/payment-request-button#html-js-set-up-stripe-elements

When you call this.elements.create('paymentRequestButton', { <<paymentRequestDoesNotExit>> });  

You can't pass in the PaymentRequest to the options as it does not exist.

**Comment by elucidsoft** [comment]
I fixed this in PR https://github.com/richnologies/ngx-stripe/pull/87

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.
