### ISSUE TITLE
Prod build in Angular 6, From stripeService.elements, 'elements' of undefined

### ISSUE THREAD

**Issue by sankarseran** [richnologies/ngx-stripe#40]
I'm calling the strip service in the child component, While parent componet load it self child is called and onInit is proceeded. In the normal ng serve it's working fine. But in the prod build it's throwing error like 
`Cannot read property 'elements' of undefined` 
`import { StripeService, Elements, Element as StripeElement, ElementsOptions } from 'ngx-stripe';`
`constructor(private stripeService: StripeService) {}`
`ngOnit() {
  this.stripeService.elements(this.elementsOptions).subscribe(elements => {
      this.elements = elements;
      // To do mount the elements
  });
}`

**Comment by krackerman** [comment]
I had a similar issue. Unfortunately I do not know why this fixed it. 

In the module I have:

NgxStripeModule.forChild(settings.stripe.publishableKey). You can try explicitly setting the publishKey you get from stripe:

NgxStripeModule.forChild('pk_test***************'),

this may or may not help. I did manage to fix it by adding

import { NgxStripeModule } from 'ngx-stripe';

to the app.module.ts file while I was debugging and it fixed my problem. I am still looking into the cause but if you need a quick fix or running out of ideas try it. Hope it helps

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.

**Comment by saascharge** [comment]
hello, I actually do have the same issue in the same context - did you find a workaround?

**Comment by BruneXX** [comment]
Same issue here, and it's happening in same context... same question, is there a workaround? I'm using ngx-stripe **v10.x.x** I'm going to try **v11.0.0** right now..

**Comment by BruneXX** [comment]
I've found the issue, this issue is coming due to wrong publishable key, problem solved, hope this help someone else.

**Comment by richnologies** [comment]
Thanks a lot @BruneXX, really helpful. 

Could you elaborate a bit more? Did you try to use your test key instead of the live one or did you try a completely different key?

I will try to replicate and add better error messaging to help others. Also, I will create a new section in the sections and add the link here.
