### ISSUE TITLE
ngx-stripe-card doesn't show credit card fields in iOS

### ISSUE THREAD

**Issue by sidorkalinin** [richnologies/ngx-stripe#41]
Hi @richnologies 
I implemented ngx-stripe sdk to our IONIC3 application.
I followed StripeCardComponent codes as shown ReadME. It works well on Android device.
But it doesn't work on iOS device.
<ngx-stripe-card [options]="cardOptions" [elementsOptions]="elementsOptions"></ngx-stripe-card>
On Android device, I see credit card field by above code. But I don't see credit card field on iOS.
Can you please help me with that issue?

Regards,
Sidor

**Comment by langos** [comment]
Simply add these code lines in your config.xml file.

<allow-navigation href="http://js.stripe.com/*" />
<allow-navigation href="https://js.stripe.com/*" />

**Comment by langos** [comment]
Simply add these code lines in your config.xml file

`<allow-navigation href="http://js.stripe.com/*" />
<allow-navigation href="https://js.stripe.com/*" />`

**Comment by Sampath-Lokuge** [comment]
@sidorkalinin Have you found the solution?

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.
