### ISSUE TITLE
How to use for non- stripe element forms

### ISSUE THREAD

**Issue by mdelgadov** [richnologies/ngx-stripe#43]
I don't use stripe elements, thus, when I try to get the token,  I can't use the element overload:

this.stripeService.getToken(this.card, {name})…

Also, this other version doesn't work either... at least in typescript:

this.stripeService.getToken({number, exp_month, exp_year, cvc}, {name})…

Typescript says the object is not an PII...

What should I pass when I'm not using elements?

Thanks in advance...
Miguel Delgado

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.
