### ISSUE TITLE
How to set class

### ISSUE THREAD

**Issue by astr0sl0th** [richnologies/ngx-stripe#54]
How do I set the class for the form like in the docs:

`registerElements([cardNumber, cardExpiry, cardCvc], 'example3');`

**Comment by spencercope4** [comment]
@astr0sl0th did you ever figure out any solution here?

**Comment by astr0sl0th** [comment]
Nope sorry, I am mainly using react and vue these days the support for 3rd party components seems better or more actively maintained. You could manually check which classes are being applied with dev tools and override those. I did something like that in the end.

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.
