### ISSUE TITLE
Apple Pay issue in Iphone X after setting the website as "Add to home Screen"

### ISSUE THREAD

**Issue by ranganathumesh** [richnologies/ngx-stripe#56]
Good Day! Team,

Issue context: I am using Stripe as the payment gateway and using ngx-stripe package in Angular 6 Single page application. In Iphone X, If I use the safari browser and pay using the Apple pay the whole process works fine, But if you save the web site as "Add to home screen" and try to place the order. Token call back not happening. listenPaymentRequest() in the PaymentComponent.txt not getting called.

Attached the custom service and component code below.

[CustomPaymentService.txt](https://github.com/richnologies/ngx-stripe/files/2809749/CustomPaymentService.txt)
[PaymentComponent.txt](https://github.com/richnologies/ngx-stripe/files/2809750/PaymentComponent.txt)

Note: Its working fine in other iPhone's through safari browser or if you do "Add to home screen" as a  shortcut.

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.
