### ISSUE TITLE
How to use this with ideal for stripe?

### ISSUE THREAD

**Issue by Sireini** [richnologies/ngx-stripe#59]
I want to implement stripe ideal but I only see a stripe-card component do you allready provide sush a component for bank usage?

If not could you give me head start so I can fork your repo and implement this in your lib folder :)

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.
