### ISSUE TITLE
Use @types for stripe-v3

### ISSUE THREAD

**Issue by DaSchTour** [richnologies/ngx-stripe#60]
I would like to suggest to use @types/stripe-v3 instead of own typings to be sure that this is interoperable and avoid type collisions.

**Comment by dottodot** [comment]
Trouble is @types/stripe-v3 isn't up to date as it doesn't include support for Payment intents

**Comment by decoursin** [comment]
It seems that it now supports payment intents: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/stripe-v3.

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.
