### ISSUE TITLE
ERROR in node_modules/ngx-stripe/lib/services/stripe.service.d.ts(20,26): error node_modules/ngx-stripe/lib/services/stripe.service.d.ts

### ISSUE THREAD

**Issue by jokerxvier06** [richnologies/ngx-stripe#65]
Error when I run ng serve see error below : 

ERROR in node_modules/ngx-stripe/lib/services/stripe.service.d.ts(20,26): error
node_modules/ngx-stripe/lib/services/stripe.service.d.ts(21,15): 

How can I fixed this.

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.
