### ISSUE TITLE
In the latest version (7.4.0) HandleCardPaymentOptions interface does not have a "type".

### ISSUE THREAD

**Issue by BjornGameDev** [richnologies/ngx-stripe#68]
The handleCardPaymentOptions interface does not have a 'type'.

**projects/ngx-stripe/src/lib/interfaces/payment-intent.ts:**
```
export function isHandleCardPaymentOptions(
  handleCardPaymentOptions: any
): handleCardPaymentOptions is HandleCardPaymentOptions {
  return 'type' in handleCardPaymentOptions;
}
```

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.
