### ISSUE TITLE
Support handleCardSetup(...)

### ISSUE THREAD

**Issue by menzerath** [richnologies/ngx-stripe#75]
**Is this a feature request or a bug report?**
feature request

**What's gone wrong?**
While making sure our application is SCA-compliant and we can handle 3-D secure cards properly I wanted to use Stripe's new `handleCardSetup(...)` functions (see [here](https://stripe.com/docs/stripe-js/reference#stripe-handle-card-setup) and [here](https://stripe.com/docs/stripe-js/reference#stripe-handle-card-setup-no-element)).  
Unfortunately it is not yet supported by ngx-stripe.

Are there any plans on supporting those functions?

**Comment by nde-mesdocteurs** [comment]
SCA is coming in less than 2 months so I would be nice to be added really soon ... :)

**Comment by bhushankumar-developer** [comment]
waiting for this.

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.
