### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by borjalo** [richnologies/ngx-stripe#77]
**Is this a feature request or a bug report?**
Bug report

**What's gone wrong?**
I am trying to use handleCardSetup() function but an error appears.

`TypeError: Object(...) is not a function`

**What was meant to happen?**
`handleCardSetup()` should be working correctly

**Steps to reproduce**

**Other information**

**Comment by borjalo** [comment]
Solved updating rxjs to version 6.5.3 and rxjs-compat to 6.5.3

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.
