### ISSUE TITLE
Adding card holder name with handleCardSetup() #33

### ISSUE THREAD

**Issue by vali-munteanu** [richnologies/ngx-stripe#82]
Hello,

I'm creating a stripe subscription and I can't figure when and where to pass on the card holder name. Should it be passed somewhere in `handleCardSetup` arguments?

**Comment by richnologies** [comment]
Please have a look at this example: https://richnologies.gitbook.io/ngx-stripe/examples#collect-payment-intent
Is for Payment Intents, but the equivalent for Setup Intents works in a very similar way. 

I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.
