### ISSUE TITLE
showIcon:true not functioning for cardNumber element? version 9.0.2

### ISSUE THREAD

**Issue by aylmercarson** [richnologies/ngx-stripe#91]
this.stripeService.elements(this.elementsOptions)
      .subscribe(elements => {
        this.elements = elements;
        // Only mount the element the first time
        if (!this.cardNumber) {
          this.cardNumber = elements.create("cardNumber", {
            showIcon: true,
            style: elementStyles
          });
          this.cardNumber.mount("#cardNumber");
        }
        if (!this.cardExpiry) {
          this.cardExpiry = this.elements.create('cardExpiry', {
            style: elementStyles
          });
          this.cardExpiry.mount('#cardExpiry');
        }
        if (!this.cardCvc) {
          this.cardExpiry = this.elements.create('cardCvc', {
            style: elementStyles
          });
          this.cardExpiry.mount('#cardCvc');
        }
      });

but i think this is now an available option for this field?
but a great repo nevertheless. and much appreciated.

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.
