### ISSUE TITLE
Latest stripejs implementation

### ISSUE THREAD

**Issue by egbertmza** [richnologies/ngx-stripe#93]
**Is this a feature request or a bug report?**
feature

**What's gone wrong?**
the handleCardPayment function has been deprecated by stripe. Hoping to see updated functions in ngx-stripe. from stripe docs ... 
"handleCardPayment has been renamed to confirmCardPayment. In addition to the rename, we have slightly modified the arguments. These changes do not affect the behavior of the method. While we have no plans to ever remove support for handleCardPayment, we think the new name and arguments are easier to understand and better convey what the method is doing."

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.

The new version of the library contains all the missing API from Stripe
